### ISSUE TITLE
merge this mod into the original

### ISSUE THREAD

**Issue by eristhea** [MikhailTapio/Ramel-Reforged#1]
while it's not against the license, it's a bit rude to make your own fork without telling me. I would be happy to give you a split of my curse points if we merged the two mods into an xplat system and put them on the original page.

**Comment by eristhea** [comment]
oh in addition -- I want to implement the same config you did into the original, for consistency. that's much harder without you making this open-source

**Comment by eristhea** [comment]
@MikhailTapio little update -- I'm merging this mod's features back into the original. xplat support for neoforge will come next

**Comment by VulpesStella** [comment]
Of course! I'm sorry I didn't see this in time.

**Comment by VulpesStella** [comment]
@ix0rai Considering there are more downloads on my page at the moment, maybe it's getting better promotion. I'll pass on ramel reforged's curseforge page if you'd like.
